# Generated by Django 5.0.7 on 2024-07-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_img', models.ImageField(upload_to='')),
                ('post_description', models.TextField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('shares', models.IntegerField()),
                ('saved', models.IntegerField()),
            ],
        ),
    ]
