# Generated by Django 5.0.7 on 2024-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_post_id_alter_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
